name: Pacific Design Office
favicon: null
layout_spectrum: 0.25538
typography_spectrum: 0.44584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ccd6cf'
    - '#ffffff'
    - '#e9e5d5'
    - '#e6ebe8'
    - '#f3f3f3'
  brandStrength: 0.7508884170092642
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
